package grapefruit.command.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a parameter of a command handler method to be
 * a command flag. A corresponding {@link grapefruit.command.argument.FlagArgument}
 * will be generated by the code generator module.
 *
 * @see grapefruit.command.argument.FlagArgument
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.PARAMETER)
public @interface Flag {

    /**
     * The name of the flag. By default, the parameter name is used.
     */
    String name() default "";

    /**
     * The shorthand of the flag. By default <code>name.charAt(0)</code>
     * is used. This means that the flag name is resolved first.
     */
    char shorthand() default ' ';

    /**
     * If {@link Flag#name()} is a blank string, the parameter's name will be used
     * as a replacement. If this option is set to true (which it is by default),
     * {@code camelCase} parameter names are turned into {@code kebab-case} names,
     * which might be desirable for flag names.
     */
    boolean hyphenate() default true;
}
