GROUP=com.tomushimano.grapefruit
POM_ARTIFACT_ID=grapefruit
VERSION_NAME=3.3.0

POM_NAME=Grapefruit
POM_DESCRIPTION=A command-line parser library.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/adamtomi/grapefruit/

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://mit-license.org/
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/adamtomi/grapefruit/
POM_SCM_CONNECTION=scm:git:git://github.com/adamtomi/grapefruit.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/adamtomi/grapefruit.git

POM_DEVELOPER_ID=adamtomi
POM_DEVELOPER_NAME=Tamas Adam
POM_DEVELOPER_URL=https://github.com/adamtomi/