package grapefruit.command.runtime.annotation;

import grapefruit.command.runtime.argument.CommandArgument;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a parameter of a command handler method to be a
 * command argument. A corresponding {@link CommandArgument}
 * will be generated by the code generation module.
 *
 * @see CommandArgument
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.PARAMETER)
public @interface Arg {

    /**
     * The name of the argument. By default, the parameter name is used.
     */
    String name() default "";
}
